### ISSUE TITLE
Ex 3.1.2

### ISSUE THREAD

**Issue by allen-gueco1** [ulfaslak/computational_analysis_of_big_data_2018_fall#2]
> Ex. 3.1.2: Using this list you now want to download all data you can about each character. However, because this is potentially Big Data, you cannot store it your computer's memory. Therefore, you have to store it in your harddrive somehow.

>Create three folders on your computer, one for heroes, one for villains, and one for ambiguous.
For each character, download the markup on their pages and save in a new file in the corresponding hero/villain/ambiguous folder.

How do we know if a character is ambiguous? Did you also want us to make a separate .txt for each character in the category?

**Comment by ulfaslak** [comment]
Good question. A character is ambiguous if it is both listed as a hero and as a villain. I suggest you create a folder for each of the three classifications.
