### ISSUE TITLE
Ex. 3.2.1

### ISSUE THREAD

**Issue by allen-gueco1** [ulfaslak/computational_analysis_of_big_data_2018_fall#3]
> Extract the length of the page of each character, and plot the distribution of this variable for each class (heroes/villains/ambiguous). Can you say anything about the popularity of characters in the Marvel universe based on your visualization?

I request a page with prop=revisions and rvprop=size and I get this json file:
{u'batchcomplete': u'', u'query': {u'pages': {u'2005010': {u'ns': 0, u'pageid': 2005010, u'revisions': [{u'size': 29613}], u'title': u'Annihilus'}}}}

For me to reach the size, I need to use the page id but that changes for each character. How can I generalize that so I can do it for all characters?

**Comment by ulfaslak** [comment]
On a dictionary object you can call the ´.values()` method to get a list of the values. So you let's say your `dict` object is called `my_dict`. To reach the `size`, do:

```PYTHON
my_dict['query']['pages'].values()[0]['revisions'][0]['size']
```

(Also apologies for the wait... holiday)
