### ISSUE TITLE
Ex 5.1.2

### ISSUE THREAD

**Issue by allengueco** [ulfaslak/computational_analysis_of_big_data_2018_fall#4]
For some reason, when I am plotting the distribution of the split entropy of all features, I get a graph with random spikes: 
![entropyinitial](https://user-images.githubusercontent.com/40132316/46169011-41d48900-c29a-11e8-894a-8aa45ec46ef8.JPG)
Why could this be?

>Write a function that computes the weighted average entropy of a split, given the data and team (name or id) on which to split the data.

Also, what did you mean by weighted average entropy of a split?

**Comment by ulfaslak** [comment]
This does not exactly look right. Not sure what the problem could be, but I'm guessing you are not computing the average weighted entropy right.

If you look in my slides from yesterday I give an example of how to compute the split entropy on page 18-23. The idea is that:
1. The question you ask to your data ("do you lay eggs" or "are you affiliated with the X-Men alliance?") splits the data into to two subsets, one that answers yes to the question and one that answers no.
2. In each of these subsets you can then compute the entropy of distribution of target values. In other words, if, say, in your first subset (the ones that answered "yes" and this were all affiliated with X-Men), there are 90% heroes, 3% villains and 7% ambiguous, the entropy of that *distribution* would be `shannon_entropy([0.9, 0.03, 0.07])`.
    * You compute the target entropy of both your subsets.
3. The weighted average entropy you can then compute by averaging the two numbers, with the twist that each term has to be weighted by how large the subset it estimates the entropy of is. Example: If the X-Men affiliated subset is 30 large and the non-X-Men subset is 1000, then the weighted average is:

```Python
30. / 1030 * shannon_entropy_X_Men + 1000. / 1030 * shannon_entropy_non_X_Men
```
